export const apiPlaceholders = {
  auth: {
    login: 'POST /api/auth/login',
    forgotPassword: 'POST /api/auth/forgot-password',
    session: 'GET /api/auth/session',
    logout: 'POST /api/auth/logout',
  },
  employee: {
    profile: 'GET /api/me',
    updateProfile: 'PUT /api/me',
    updateProfilePhoto: 'PUT /api/me/profile-photo',
    notifications: 'GET /api/me/notifications',
    documents: 'GET /api/me/documents',
    uploadDocument: 'POST /api/me/documents',
    deleteDocument: 'DELETE /api/me/documents/:documentId',
    onboarding: 'GET /api/me/onboarding',
    submitOnboarding: 'POST /api/me/onboarding/submit',
    timesheets: 'GET /api/me/timesheets',
    saveTimesheet: 'POST /api/me/timesheets',
    submitTimesheet: 'POST /api/me/timesheets/:id/submit',
    leaveBalances: 'GET /api/me/leave/balances',
    leaveRequests: 'GET /api/me/leave/requests',
    createLeaveRequest: 'POST /api/me/leave/requests',
    payslips: 'GET /api/me/payroll/payslips?month=:month&year=:year',
  },
  employer: {
    dashboard: 'GET /api/admin/dashboard',
    employees: 'GET /api/admin/employees',
    createEmployee: 'POST /api/admin/employees',
    updateEmployee: 'PUT /api/admin/employees/:id',
    employeeDetail: 'GET /api/admin/employees/:id',
    employeeDocuments: 'GET /api/admin/employees/:id/documents',
    uploadEmployeeDocument: 'POST /api/admin/employees/:id/documents',
    clients: 'GET /api/admin/clients',
    createClient: 'POST /api/admin/clients',
    updateClient: 'PUT /api/admin/clients/:id',
    clientDocuments: 'GET /api/admin/clients/:id/documents',
    uploadClientDocument: 'POST /api/admin/clients/:id/documents',
    entities: 'GET /api/admin/entities',
    createEntity: 'POST /api/admin/entities',
    updateEntity: 'PUT /api/admin/entities/:id',
    entityDocuments: 'GET /api/admin/entities/:id/documents',
    uploadEntityDocument: 'POST /api/admin/entities/:id/documents',
    approvals: 'GET /api/admin/approvals',
    approveItem: 'POST /api/admin/approvals/:id/approve',
    rejectItem: 'POST /api/admin/approvals/:id/reject',
    onboarding: 'GET /api/admin/onboarding',
    markOnboardingActive: 'POST /api/admin/onboarding/:id/activate',
    payrollRuns: 'GET /api/admin/payroll-runs',
    createPayrollBatch: 'POST /api/admin/payroll-runs',
    uploadPayslip: 'POST /api/admin/payroll/payslips',
    reports: 'GET /api/admin/reports',
    settings: 'GET /api/admin/settings',
    saveSettings: 'PUT /api/admin/settings',
  },
};

export function showApiPlaceholder(label, endpoint) {
  window.alert(`${label}\n\nBackend API placeholder:\n${endpoint}`);
}
